### ISSUE TITLE
Рефакторинг: как поменять функцию  yaml_to_csv() 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/ssg-dataset#13]
https://github.com/epogrebnyak/ssg-dataset/blob/7675e623d24ed5169423695180690d9105b637af/src/ssg/stars.py#L171-L198

Это основная функция пакета ssg, она нужна для того чтобы из yaml файла сделать CSV 

Пример использования - в examples/update.py 

Вопрос коллегам: как можно улучшить/изменить  эту функцию и что-нибудь вокруг нее?

**Comment by AntonBoch1244** [comment]
https://github.com/epogrebnyak/ssg-dataset/blob/7675e623d24ed5169423695180690d9105b637af/src/ssg/stars.py#L188-L193

Вообще для чего функция there в функции? Можно же переиспользовать то что находится в return'е этой функции.
Держать функцию внутри функции мне кажется не имеет особого смысла.

**Comment by AntonBoch1244** [comment]
https://github.com/epogrebnyak/ssg-dataset/blob/7675e623d24ed5169423695180690d9105b637af/src/ssg/stars.py#L154-L158

Для отладки где что сломалось полезно, но лучше избавиться от использования переменных здесь.

**Comment by epogrebnyak** [comment]
Давайте я буду записывать предложения по рефакторингу:

- [ ] @AntonBoch1244: `there()` внутри `yaml_to_csv()` выглядит странно, можно ее убрать

**Comment by AntonBoch1244** [comment]
https://github.com/epogrebnyak/ssg-dataset/blob/7675e623d24ed5169423695180690d9105b637af/src/ssg/stars.py#L194-L197

Метаданные мне кажется должны быть в отдельной функции.

**Comment by epogrebnyak** [comment]
- [ ] @AntonBoch1244:  запись метаданных должна быть в отдельной функции

Это очень поддерживаю - сейчас `yaml_to_csv()` делает несколько вещей, которые можно выделить в разные функции

**Comment by epogrebnyak** [comment]
Из общих соображений, что нам нужно в первую очередь:

- [ ]  end-to-end тест, который проверяет не все ли развалилось (это самое важное)
- [ ] аннотации типов - сейчас в пакете совсем не используются
- [ ] нет докстринга в функции
- [ ] основная функция не экспортируется пакетом `ssg`
- [ ] нет `__all__`
- [ ] про оснонвую функцию ничего не сказано в докстринге модуля

Это все касается изменений еще до рассмотрения логики самой функций, в принцпе эти изменения довольно общие

Из bad smells функции и окружения:

- [ ] у `yaml_to_csv()` очень много аргументов, больше трех - повод задуматься
- [ ] проверка значений языка (python, ruby) записана в код, а не yaml - неудобно если появится генератор на новом языке (хотя не первое, что нужно менять)
- [ ] где-то у нас pathlib, где-то os для работы с файлами (не страшно, но непоследовательно)

Может быть что-то еще что-то предложит?

**Comment by AntonBoch1244** [comment]
Я думаю от pathlib можно отказаться в сторону модуля os.path.

Python в зависимости от стандарта ОС сам сконвертит путь в правильный формат. Плюсом сэкономит немного памяти.

**Comment by AntonBoch1244** [comment]
Ещё более правильным действием на мой взгляд это интеграция всех функций использующих одни и те же объекты в один класс.

**Comment by epogrebnyak** [comment]
Что не хватает в начальном тесте [694c943](https://github.com/epogrebnyak/ssg-dataset/commit/694c943f12846af8f708e56633d75c7c8a41531f)? Почему это тест будет валится, а сейчас проходит?

**Comment by epogrebnyak** [comment]
> Ещё более правильным действием на мой взгляд это интеграция всех функций использующих одни и те же объекты в один класс.

Вопрос стиля - на Java бы так и делали, в питоне не обязаетльно

**Comment by epogrebnyak** [comment]
> Я думаю от pathlib можно отказаться в сторону модуля os.path.
> 
> Python в зависимости от стандарта ОС сам сконвертит путь в правильный формат. Плюсом сэкономит немного памяти.

Где-то удобнее Path, где-то os.path (например, если на входе строки и на выходе строка). Экономия памяти ничтожна, это при рефакторинге такого типа задач не актуально.

**Comment by epogrebnyak** [comment]
Общий пайплайн обработки данных у нас такой:

```Path (путь YAML файла) -> str (его содержимое в виде текста)-> Dict (сам YAML как словарь) -> Dict (распакованный YAML) -> List[SSG] (список статических генераторов) -> List[Tuple[SSG, RepoState]] (список генераторов и данных из Github) -> DataFrame (широкий датафрейм) -> list[str] (уменьшаем набор столбцов) -> DataFrame (итоговый датафрейм) -> Path (куда записываем)```

Из того что пришло в голову по ходу рефакторинга:

- [ ] разделить обращение к Github (Repostate) и создание списка (SSG) в разные модули
- [ ] формат даты в RepoState можно жестке контролировать
- [ ] вставить проверку типов в датафрейме pandera или аналогичную
- [ ] открытый вопрос с метаданными - сам формат pandas и CSV не очень подходят
- [ ] не производили сборку нового датасета, на сл.выходные

Галочками помечу выше, что отрефаторили.

**Comment by epogrebnyak** [comment]
По факту - осталось многодукментации, если кто-то захочет написать пару докстрингов - welcome (например, в двум эксспортируемым функциям). Хороший докстринг - тоже навык, можно разобрать на примере.

**Comment by epogrebnyak** [comment]
Оставлю открытым до следующих выходных - 25.06, далее - закрываю.
