### ISSUE TITLE
Add Pydantic validation [0.5h]

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/ssg-dataset#22]
https://github.com/epogrebnyak/ssg-dataset/blob/fadae342eff4b886a77f8c4523f5ebfe450ba508/src/ssg/stars.py#L44-L45

Add validation for: 
- github handle (must have slash)
- programming language is in hardcoded list 

https://pydantic-docs.helpmanual.io/usage/validators/

**Comment by finrod-felagund23** [comment]
@validator("lang")
    def lang_field_must_be_one_of_allowed(cls, value: str) -> str:
        if value.lower() not in allowed_languages:
            raise ValueError('Incorrect language name')
        return value

    @validator("github_handle")
    def github_handle_field_must_contain_slash(cls, value: str) -> str:
        if '/' not in value:
            raise ValueError("github_handle must contain '/'")
        return value

Allowed only this languages or more?

**Comment by epogrebnyak** [comment]
Maybe more versobe error message on allowed languages? Got <value>, expected any of <list of allowed values>.

Let's stick for just js for Javascript, no options

**Comment by epogrebnyak** [comment]
Can also use own error type (if you prefer):

```
class ValidationError(ValueError):
   pass
```

**Comment by finrod-felagund23** [comment]
Yes, in pydantic exist ValidationError exception, but it use more than 1 positional args. I will make own exception, ok. And more verbose message

**Comment by epogrebnyak** [comment]
It looks from docs that we raise ValueError, but can catch `pydantic.ValuationError` - so maybe start without own error class, just leave ValueError in validator code for simpolicity (otherwise we can run into conflict of names, etc)

**Comment by finrod-felagund23** [comment]
Maybe make subclass OwnValidationError, because ValueError can raise from other places of project and can confuse us?

**Comment by epogrebnyak** [comment]
a26f0c9f06562b43c96650422c9171c2f0cfa313
