### ISSUE TITLE
SVG badge shown in bleak color

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/ssg-dataset#30]
https://github.com/epogrebnyak/ssg-dataset/blob/9955b69095d24c68eb955ef3d73e8a6f758701a1/streamlit_app.py#L87-L94

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/175833122-cc09bfa6-6ef2-4cec-b4d2-fc5897fd4e2c.png)

**Comment by finrod-felagund23** [comment]
Problem with browser
