### ISSUE TITLE
fix hyperlink

### ISSUE THREAD

**Issue by harryrichman** [epogrebnyak/ssg-dataset#33]
In this line, the hyperlink for "mkdocs-material" instead redirects to the VitePress repository:
https://github.com/epogrebnyak/ssg-dataset/blob/b256abd7bdcc7ddab7a1309644bc6fc447d7f521/app/pages/4_%F0%9F%8C%9F_My_favorites.py#L29

**Comment by epogrebnyak** [comment]
@harryrichman thanks for poitignout will fix
