### ISSUE TITLE
Suggestion for colors

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [epogrebnyak/ssg-dataset#9]
Consider using the Github colors for the bar-chart of programming languanges?
For instance, the Blue color chosen for Go is very close to the color Github uses for Python.

Choosing the a color-coding a lot of people are familiar with reduces the need to consult the legend, and would IMHO make your visualization better, as it's easier to just focus on the "real" contents.

But overall nice work (even with the colors ;) )  👍

**Comment by epogrebnyak** [comment]
Very subtle idea, thank you! Colors in the Streamlit app are quite terrible. 

Found an encoding, will update with anew version: https://github.com/ozh/github-colors
